server:
  port: 8080
spring:
  jackson:
    default-property-inclusion: non_null # 全局jackson配置
  datasource:
    db-mxd:
      jdbc-url: jdbc:mysql://localhost:3306/db_mxd?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    db-lol:
      jdbc-url: jdbc:mysql://localhost:3306/db_lol?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    db-sys:
      jdbc-url: jdbc:mysql://10.21.128.6/db_sys?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: longmaster
      driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-idle: 8
        max-active: 8
        min-idle: 0

saas:
  url: https://interface.39.net/saas-triage/
  appid: quickapp
  secret: 1f112a9784214c6fab2552d0811034ed
